sucessfully load word dictionary with shape21224
analyze article 0
analyze article 1
analyze article 2
analyze article 3
analyze article 4
analyze article 5
analyze article 6
analyze article 7
analyze article 8
analyze article 9
analyze article 10
analyze article 11
analyze article 12
analyze article 13
analyze article 14
analyze article 15
analyze article 16
analyze article 17
analyze article 18
analyze article 19
analyze article 20
analyze article 21
analyze article 22
analyze article 23
analyze article 24
analyze article 25
analyze article 26
analyze article 27
analyze article 28
analyze article 29
analyze article 30
analyze article 31
analyze article 32
analyze article 33
analyze article 34
analyze article 35
analyze article 36
analyze article 37
analyze article 38
analyze article 39
analyze article 40
analyze article 41
analyze article 42
analyze article 43
analyze article 44
analyze article 45
analyze article 46
analyze article 47
analyze article 48
analyze article 49
analyze article 50
analyze article 51
analyze article 52
analyze article 53
analyze article 54
analyze article 55
analyze article 56
analyze article 57
analyze article 58
analyze article 59
analyze article 60
analyze article 61
analyze article 62
analyze article 63
analyze article 64
analyze article 65
analyze article 66
analyze article 67
analyze article 68
analyze article 69
analyze article 70
analyze article 71
analyze article 72
analyze article 73
analyze article 74
analyze article 75
analyze article 76
analyze article 77
analyze article 78
analyze article 79
analyze article 80
analyze article 81
analyze article 82
analyze article 83
analyze article 84
analyze article 85
analyze article 86
analyze article 87
analyze article 88
analyze article 89
analyze article 90
analyze article 91
analyze article 92
analyze article 93
Traceback (most recent call last):
  File "dataloader.py", line 209, in <module>
    article.save_wdx()
  File "dataloader.py", line 66, in save_wdx
    self.est_dict(self.articles)
  File "dataloader.py", line 53, in est_dict
    with open(filepath) as f:
FileNotFoundError: [Errno 2] No such file or directory: './txt/Cybertrust'
